In [1]:
import pandas as pd

In [5]:
cancer=pd.read_csv("C:\\Users\\Lenovo PC\\Desktop\\python\\dataset\\breast_cancer.csv")
cancer.head()

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,class,doctor_name
0,1000025,5.0,1.0,1,1,2,1,3.0,1.0,1,benign,Dr. Doe
1,1002945,5.0,4.0,4,5,7,10,3.0,2.0,1,benign,Dr. Smith
2,1015425,3.0,1.0,1,1,2,2,3.0,1.0,1,benign,Dr. Lee
3,1016277,6.0,8.0,8,1,3,4,3.0,7.0,1,benign,Dr. Smith
4,1017023,4.0,1.0,1,3,2,1,3.0,1.0,1,benign,Dr. Wong

In [ ]:
#get dummies=is used to convert strings to numbers and cerates various columns

In [7]:
x=pd.get_dummies(cancer['class'])
x.head()

   benign  malignant
0       1          0
1       1          0
2       1          0
3       1          0
4       1          0

In [ ]:
#dropna will detete null values and drop will delete anything

In [8]:
#drop class column
cancer.drop(['class'],axis=1,inplace=True)

In [9]:
cancer.head()

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,doctor_name
0,1000025,5.0,1.0,1,1,2,1,3.0,1.0,1,Dr. Doe
1,1002945,5.0,4.0,4,5,7,10,3.0,2.0,1,Dr. Smith
2,1015425,3.0,1.0,1,1,2,2,3.0,1.0,1,Dr. Lee
3,1016277,6.0,8.0,8,1,3,4,3.0,7.0,1,Dr. Smith
4,1017023,4.0,1.0,1,3,2,1,3.0,1.0,1,Dr. Wong

In [10]:
#now fill the dummy variables in the dataset
cancer=pd.concat([cancer,x],axis=1)
cancer.head()

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,doctor_name,benign,malignant
0,1000025,5.0,1.0,1,1,2,1,3.0,1.0,1,Dr. Doe,1,0
1,1002945,5.0,4.0,4,5,7,10,3.0,2.0,1,Dr. Smith,1,0
2,1015425,3.0,1.0,1,1,2,2,3.0,1.0,1,Dr. Lee,1,0
3,1016277,6.0,8.0,8,1,3,4,3.0,7.0,1,Dr. Smith,1,0
4,1017023,4.0,1.0,1,3,2,1,3.0,1.0,1,Dr. Wong,1,0

In [ ]:
#label encoder(=alphabetical order which consists of first alphabet=0,2nd alphabet=1,3rd=2,same vlaue=same index)#modification of get dummies because various columns are not created rather changed in that column
#label encoder is a package of sklearn(scientific kit learn)

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
lec=LabelEncoder()

In [13]:
#to apply=fit_transform
cancer['doctor_name']=lec.fit_transform(cancer['doctor_name'])

In [14]:
cancer.head()

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,doctor_name,benign,malignant
0,1000025,5.0,1.0,1,1,2,1,3.0,1.0,1,0,1,0
1,1002945,5.0,4.0,4,5,7,10,3.0,2.0,1,2,1,0
2,1015425,3.0,1.0,1,1,2,2,3.0,1.0,1,1,1,0
3,1016277,6.0,8.0,8,1,3,4,3.0,7.0,1,2,1,0
4,1017023,4.0,1.0,1,3,2,1,3.0,1.0,1,3,1,0

In [16]:
#group by
cancer.groupby(by=['doctor_name','benign']).size() #acc to the observation,there are only four doctors #1st doctor has treated 58 malignant  patients,2nd alphabetically doctor has treated 127 benign patients

doctor_name  benign
0            0          58
             1         127
1            0          60
             1         121
2            0          74
             1         102
3            0          49
             1         108
dtype: int64

In [17]:
cancer.isnull().sum() #checking missing values

patient_id               0
clump_thickness          1
cell_size_uniformity     1
cell_shape_uniformity    0
marginal_adhesion        0
single_ep_cell_size      0
bare_nuclei              2
bland_chromatin          4
normal_nucleoli          1
mitoses                  0
doctor_name              0
benign                   0
malignant                0
dtype: int64

In [19]:
cancer['bland_chromatin'].fillna(cancer['bland_chromatin'].mean(),inplace=True) #fill bland chromatin with mean

In [20]:
cancer.head()

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,doctor_name,benign,malignant
0,1000025,5.0,1.0,1,1,2,1,3.0,1.0,1,0,1,0
1,1002945,5.0,4.0,4,5,7,10,3.0,2.0,1,2,1,0
2,1015425,3.0,1.0,1,1,2,2,3.0,1.0,1,1,1,0
3,1016277,6.0,8.0,8,1,3,4,3.0,7.0,1,2,1,0
4,1017023,4.0,1.0,1,3,2,1,3.0,1.0,1,3,1,0

In [21]:
cancer.isnull().sum()

patient_id               0
clump_thickness          1
cell_size_uniformity     1
cell_shape_uniformity    0
marginal_adhesion        0
single_ep_cell_size      0
bare_nuclei              2
bland_chromatin          0
normal_nucleoli          1
mitoses                  0
doctor_name              0
benign                   0
malignant                0
dtype: int64